dct:
  config1_f32:
    melFilters: 40
    dctOutputs: 5
    type: "f32"

melfilter:
  config1_f32:
    fftlength: 1024
    fmin: 64
    fmax: 8000
    samplingRate : 16000
    melFilters: 40
    type: "f32"

window:
  config1_f32:
    fftlength: 1024
    type: "f32"
    win: "hanning"
