dct:
  config1_f32:
    melFilters: 30
    dctOutputs: 12
    type: "f32"

melfilter:
  config1_f32:
    fftlength: 1024
    fmin: 64
    fmax: 8000
    samplingRate : 16000
    melFilters: 30
    type: "f32"

window:
  config1_f32:
    fftlength: 1024
    type: "f32"
    win: "hanning"
